name: MVP Hunter Reminder

on:
  schedule:
    - cron: "50 1-3/2,11-23/2 * * *"
  workflow_dispatch:

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Get current hour (GMT-3)
        id: time
        run: |
          hour=$(TZ=America/Sao_Paulo date +'%H')
          echo "time=$hour" >> $GITHUB_ENV
          echo "Hora capturada: $hour"

      - name: Run JavaScript to get the message
        id: get-message
        run: |
          message=$(node ./scripts/getMessage.js)
          echo "message=$message" >> $GITHUB_ENV
          echo "Mensagem retornada: $message"
        env:
          time: ${{ env.time }}
          message: ${{ env.message }}

      - name: Send message to Discord Webhook
        run: |
          curl -X POST ${{ secrets.DISCORD_WEBHOOK_URL }} \
          -H "Content-Type: application/json" \
          -d "{\"content\": \"${{ env.message }}\"}"
        env:
          message: ${{ env.message }}
