name: MVP Hunter Reminder

on:
  schedule:
    - cron: "50 1-3/2,11-23/2 * * *"
  workflow_dispatch:

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Get and Run Message Script
        id: get-message
        run: |
          hour=$(TZ=America/Sao_Paulo date +'%H')  # Obtém a hora com o fuso horário de São Paulo
          
          # Verifica se a execução é manual
          if [[ $GITHUB_EVENT_NAME == "workflow_dispatch" ]]; then
            prefix="ISSO É UM TESTE\n"
          else
            prefix=""
          fi

          # Script Node.js para obter a mensagem
          message=$(node -e "
          const messages = { 
            '00': 'AAAAAAPPPPPPOOOOOOCCCCCCC',
            '08': 'Bom dia! Bora farmar a primeira wave de MVP!',
            '10': 'Segunda wave de MVP iniciando! Vamos com tudo!',
            '12': 'Hora do almoço? Mas e a wave de MVP?',
            '14': 'AAAAAAPPPPPPOOOOOOCCCCCCC',
            '16': 'Mais uma wave de MVP a caminho! Força!',
            '18': 'A noite chegou, mas o farm de MVP não acabou!',
            '20': 'Outra wave de MVP começando agora! Vamos!',
            '22': 'Última wave de MVP do dia! Vamos com tudo!'
          };
          const defaultMentions = '<@262002263101407233> <@365676086874603522>\n';
          const defaultMessage = 'MVP, bora!';
          const hour = process.env.HOUR;  // Obtém o valor da variável de ambiente HOUR
          const message = messages[hour] || defaultMessage;
          console.log(process.env.PREFIX + defaultMentions + message);
          " HOUR=$hour PREFIX="$prefix")

          # Agora a variável 'message' já contém o valor final, com o prefixo e a mensagem
          echo "message=$message" >> $GITHUB_ENV
          echo "Mensagem final para o Discord: $message"

      - name: Send message to Discord Webhook
        run: |
          # Usar a variável de ambiente diretamente no comando
          echo "Enviando mensagem: ${{ env.message }}"

          # Enviar a mensagem para o Discord com o valor final de 'message'
          curl -X POST ${{ secrets.DISCORD_WEBHOOK_URL }} \
          -H "Content-Type: application/json" \
          -d "{\"content\": \"${{ env.message }}\"}"
