name: MVP Hunter Reminder

on:
  schedule:
    - cron: "50 1-3/2,11-23/2 * * *"
  workflow_dispatch:

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Get and Run Message Script
        id: get-message
        run: |
          hour=$(TZ=America/Sao_Paulo date +'%H')
          message=$(node -e "
          const messages = { 
            '00': 'AAAAAAPPPPPPOOOOOOCCCCCCC',
            '08': 'Bom dia! Bora farmar a primeira wave de MVP!',
            '10': 'Segunda wave de MVP iniciando! Vamos com tudo!',
            '12': 'Hora do almoço? Mas e a wave de MVP?',
            '14': 'AAAAAAPPPPPPOOOOOOCCCCCCC',
            '16': 'Mais uma wave de MVP a caminho! Força!',
            '18': 'A noite chegou, mas o farm de MVP não acabou!',
            '20': 'Outra wave de MVP começando agora! Vamos!',
            '22': 'Última wave de MVP do dia! Vamos com tudo!'
          };
          const defaultMentions = '<@262002263101407233> <@365676086874603522>\n';
          const defaultMessage = 'MVP, bora!';
          const hour = process.env.HOUR;
          const message = messages[hour] || defaultMessage;
          console.log(defaultMentions + message);
          " HOUR=$hour)
          echo "message=$message" >> $GITHUB_ENV
          echo "Mensagem final: $message"

      - name: Send message to Discord Webhook
        run: |
          curl -X POST ${{ secrets.DISCORD_WEBHOOK_URL }} \
          -H "Content-Type: application/json" \
          -d "{\"content\": \"${{ env.message }}\"}"
