name: MVP Hunter Reminder

on:
  schedule:
    # Runs at 1:53, 3:53, 11:53, 13:53, 15:53, 17:53, 19:53, 21:53, 23:53 UTC which is 22:53, 00:53, 08:53, 10:53, 12:53, 14:53, 16:53, 18:53, 20:53 GMT-3
    - cron: "53 1-3/2,11-23/2 * * *"
  workflow_dispatch:

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Get current hour (GMT-3)
        id: time
        run: echo "time=$(TZ=America/Sao_Paulo date +'%H')" >> $GITHUB_ENV

      - name: Run JavaScript to get the message
        id: get-message
        run: |
          message=$(node ./scripts/getMessage.js)
          echo "message=$message" >> $GITHUB_ENV

      - name: Send message to Discord Webhook
        run: |
          curl -X POST ${{ secrets.DISCORD_WEBHOOK_URL }} \
          -H "Content-Type: application/json" \
          -d "{\"content\": \"${{ env.message }}\"}"
